services:
  db:
    image: postgres:16.6
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: example
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"




