services:
  db:
    image: postgres:16.6
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: Eric123$
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  app:
    image: my-backend:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USERNAME: test
      DB_PASSWORD: Eric123$





