server:
  port: 8080

spring:
  application:
    name: homework
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: h2
    url: jdbc:h2:mem:example;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:schema

logging:
  level:
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure: INFO

mybatis:
  type-aliases-package: com.ontario.homework.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
