server:
  port: 8080

spring:
  application:
    name: homework
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: postgres
    url: jdbc:postgresql://localhost:5432/example
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:schema

logging:
  level:
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure: INFO

mybatis:
  type-aliases-package: com.ontario.homework.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
